version: '3.2'
services:
  mariadb:
    container_name: sales-control-db  
    image: mariadb:10.9.4
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./mariadb:/var/lib/mysql
    tty: true
    ports:
        - 3306:3306
    networks:
          - laravel

  app:
    container_name: sales-control-app
    build:
        context: .
        args:
            USER: ${SYS_USER}
            UID: ${SYS_UID}
            GID: ${SYS_UID}
        dockerfile: Dockerfile
    image: laravel-app
    restart: unless-stopped
    environment:
        DB_CONNECTION: ${DB_CONNECTION}
        DB_HOST: ${DB_HOST}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    working_dir: /var/www/
    volumes:
        - ./:/var/www
        - ./docker/php/${INI_FILE}:/usr/local/etc/php/conf.d/local.ini
    networks: 
        - laravel
  
  nginx:
      container_name: sales-control-nginx
      image: nginx:alpine
      restart: unless-stopped
      ports: 
          - "80:80"
          - "443:443"
      volumes: 
          - ./:/var/www
          - ./docker/nginx/${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/cert.crt:/etc/nginx/cert.crt
          - ./docker/nginx/cert.key:/etc/nginx/cert.key
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      networks:
          - laravel

networks: 
    laravel:
        driver: bridge

